### ISSUE TITLE
Failed to Link due to .response file VS 2017 UE4.18

### ISSUE THREAD

**Issue by deadwizad** [liamkf/Unreal_FASTBuild#22] opened 2017-12-10 20:02 UTC
I've patched up this implementation to work with UE4.18 and VS2017.

However, if you disable

bUseUnityBuild = false
bUseSharedPCHs = false

You get this. 

```
3>7> LINK : fatal error LNK1104: cannot open file '@C:\Work\UnrealEngine\Engine\Intermediate\Build\Win64\ShaderCompileWorker\Development\ShaderCompileWorker-Core.lib.response'
3>
3>7> Failed to build Library (error 1104) 'C:\Work\UnrealEngine\Engine\Intermediate\Build\Win64\ShaderCompileWorker\Development\ShaderCompileWorker-Core.lib'
```

The response file exists.

Our game module experiences the same issues.
I can compile the engine just fine, the game module just wont have it and fails to compile 100% of the time in the same place.

Any ideas?

**Comment by rvkennedy** [comment] 2017-12-12 13:01
Can you post the text of the ShaderCompileWorker action that's created in your bff file?

**Comment by deadwizad** [comment] 2017-12-12 14:46
[fbuild.txt](https://github.com/liamkf/Unreal_FASTBuild/files/1551979/fbuild.txt)

Added it here as well for consistency.
Further notes. 

I'm on the very latest of VS2017 Community.

**Comment by nedwardsnae** [comment] 2018-01-31 15:45
Has anyone had any success resolving this issue? I'm having the same problem when trying to produce a lib for a game module with unity builds turned off.

A naive observation would be that building non-unity inflates the size of the response file and the number of objs that need to be linked. I can compile and link the same code with XGE fine though.

**Comment by nedwardsnae** [comment] 2018-02-05 17:51
For anyone who is curious about this, the cause of the issue is that once the link command exceeds a certain length, FASTBuild generates its own response file. This response file then contains the UE response file, and nested response files aren't supported. See here: https://msdn.microsoft.com/en-us/library/3te4xt0y.aspx. "It is not possible to specify the @ option from within a response file. That is, a response file cannot embed another response file."

**Comment by yass007** [comment] 2018-02-09 19:55
Fixed in the latest.

**Comment by yass007** [comment] 2018-05-07 19:23
Closing

**Closed as completed by yass007** 2018-05-07 19:23 UTC
